name             'LAMP'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures LAMP'
long_description 'Installs/Configures LAMP'
version          '0.1.0'

depends 'apache2',        '= 2.0.0'
depends 'mysql',          '= 5.6.1'
depends 'database',       '= 2.3.0'
depends 'mysql-chef_gem', '= 0.0.5'
depends 'yum-epel'
depends 'logrotate'
